apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container-edited
      image: nginx:1.28.0-perl
      ports:
        - containerPort: 80
